### PR TITLE
[Resolve #4] Fail gracefully on bad input

### LINKED ISSUE #4: Confusing failure if invalid input passed into filter
Given a call to this filter like:

```jinja
policy_document:
  {{ updated_policy_document | unquote_resolvers(output_indent=4, trim=True) }}
```

If the input does not contain a list of a dict, the filter fails confusingly like:

```
  File "/app/sceptre/sceptre/config/reader.py", line 509, in _render
    raise SceptreException(message) from err
sceptre.exceptions.SceptreException: s3-bucket-generic.yaml - unquote_resolvers - ('cannot represent an object', Undefined)
Templating vars saved to: /tmp/vars_fdup6pqa
```

The filter should fail gracefully in this scenario.

### PR DESCRIPTION
**Pull request by alex-harvey-z3q**
Given a call to this filter like:

```jinja
policy_document:
  {{ updated_policy_document | unquote_resolvers(output_indent=4, trim=True) }}
```

If the input does not contain a list or a dict, the filter fails confusingly like:

```
  File "/app/sceptre/sceptre/config/reader.py", line 509, in _render
    raise SceptreException(message) from err
sceptre.exceptions.SceptreException: s3-bucket-generic.yaml - unquote_resolvers - ('cannot represent an object', Undefined)
Templating vars saved to: /tmp/vars_fdup6pqa
```

This adds code to fail gracefully in this scenario.

Also updates dependencies to get the tests passing again.

### CODE REVIEW

**Review by zaro0508 — CHANGES_REQUESTED** [review]
this PR seems fine to me however the pre-commit job is failing.

Also this repo is still setup to build and release with CircleCI.  Sceptre has migrated away from CircleCi to GH actions therefore unit tests jobs for this project are no longer running either.   You might want to enable unit tests in GH actions.  For an example on how that's done you can take a look at the [sceptre-resolver-template test and release workflows](https://github.com/Sceptre/sceptre-resolver-template/blob/master/.github/workflows/)

**Comment by alex-harvey-z3q** [comment]
Not certain, but I think I've done everything I can from my side!

**Comment by zaro0508** [comment]
@alexharv074 I have fixed pre-commit and updated this repo to run tests on GH actions with PR #8 and #9.

**Comment by zaro0508** [comment]
@alexharv074 i have updated this PR with master, but I think i made a mistake by not changing the `types-PyYAML` dependency to `pyyaml`.   I think you wanted to set it to `pyyaml`, correct?  if so please update this PR.

**Review by zaro0508 — APPROVED** [review]

**Review by zaro0508 — APPROVED** [review]
NVM @alexharv074, i have updated the pyyaml dependency.

**Pull request merged**
